### ISSUE TITLE
dev (pre)releases

### ISSUE THREAD

**Issue by fopina** [surface-security/surface#86]
### Related software versions

*

### Description

I'll start using this branching/release strategy in my projects and I'd like to recommend it here as well.

* All PRs are done against `develop` (not `main`)
* `develop` should always have the `next` version (in `__version__`)
*  `publish-dev` workflow will publish a new pre-release (`.devX`) on every merge to `develop`
* On a less frequent basis, a stable version can be released by merging `develop` to `main`

This allows for anyone wanting to use latest to install pre-releases while keeping the stable versions "more stable" (meaning that they'd have been tested previously by those using pre-releases).

Steps to setup

* https://github.com/fopina/django-bulk-update-or-create/commit/37ea5187fac08e033d994f86dc263a2dea028e17 workflow
* Create `develop` branch from `main`
* Make `develop` the default branch
* Add protection rules to `main` and `develop` (only pull requests, no force push, etc)
* Bump version in `develop` to next planned (even if when the release comes, it's a different version due to breaking changes or whatever)

### Use cases

Faster releases, easier (actual) "beta" testing, "more stable" stable releases

**Comment by fopinappb** [comment]
I thought that process was already used since the beginning (in Surface and scanners), as all of them use docker as package.

This one was towards PyPi packages. Even if the same strategy could be used, it feels like an overwhelming amount of packages published to PyPi.

And they cannot be overwritten which means each commit in a PR would push a new package (`.dev.BRANCH.new-build-number`) to PyPi.

Main goal with `develop` approach is not to test single changes but to be able to test all of them integrated before an actual release.

Surface main is actually a `develop` so I wouldn't apply it there. But for the packages that might be used in other projects, I don't think it's the same.

While there might be a overload of using `develop` before `main`, it should be a small one. It's one extra PR (from develop to main) from time to time.  
Rest of the workflow is the same (open PRs, merge to develop).

Added benefit is that merging to develop would trigger a published package immediately without having to worry about properly versioning (it's pre-release).

After a few changes (or each month), unreleased changes could be moved to main, git tag created (package published) and version bumped in `develop`.

The preemptive bump of version (bump version *after* release in develop, instead of having to bump version *before* release in main) is also easier to *not* forget :)

But I suppose the main difference from what is currently used is what I mentioned before: ability to use a version with integrated changes (different PRs) for some time before moving to main.

**Comment by gsilvapt** [comment]
The previous process did not have granular control over what gets released, as in, everything that got merged in `main` (the default branch) would be published.

The suggestion there is only in Surface, which does not have issues with pushing packages to pypi, **although** I have thought about space consumption on GitHub's package registry. I assume something should cleanup eventually, but we do not have any routines for that currently.

But you raised a good point about `pypi` packages and "lib" style repositories, where we need even more control over what gets published, namely because of potential limitations of the registry itself (like `pypi`). The process should be different, indeed. 

I have 2 questions about the proposal above:
1. What happens when the next version is a minor or major version? Do we need to decide before what type of change will land there in the next iteration? I'm just trying to see what is the best way to manage the `__version__` file.
2. You mentioned pre-releases with `.devX`. What would be X there? The develop version, which has been updated before?

I think this structure is acceptable but will require a bit more of planning and structuring to use the versions correctly, like predicting which changes will land on the next release, if those are minor, patch or major, etc etc. Or am I exaggerating a little?

**Comment by fopina** [comment]
As a dev release, X would be just an iterative number, typically build number.

According to semver, pre-release builds should reset when version changes though that's not easy to do with GitHub actions.

As you can see in that workflow i append both ".dev" and X to the version without the commit so develop branch does not get any commits related to dev versioning.

About picking the "next" version, in that example I know I want to release 1.0.0 so I used it.

But for sake of simplicity it could be just minor bump and then review it when merging to main

**Comment by gsilvapt** [comment]
What about documenting and suggesting people to use `git+https://github.com/surface-security/...` if they want to use a dev release (or even ourselves to test features)?
I'm looking at some of the most common python packages (requests, pytest, tox, black) and they rarely have dev builds. Instead, they do have release candidates, which we could do with this type of code structure too. Seems somewhat simpler to me, controlled (we choose when to tag as release candidate and that can be rc1, 2, and as many as we need to fix issues) and without filling the registry with garbage.

What do you think about this alternative?

**Comment by fopina** [comment]
“dev” or rc is the same, afaik, so sure.

and yes, I install from git when I open a PR and want to use it while waiting for merge/release.

Again, develop was less about publishing the packages and more about having an integrated release to be used before main.

But main and using rc is fine as well (or the same IMO 😄 )

**Comment by gsilvapt** [comment]
For the RC we still need main + develop to control what gets published. I'll try to work on some of these workflows soon and ping you for a review afterwards.
I'll also try to document this discussion somewhere in the [guidelines](https://github.com/surface-security/guidelines)

**Comment by gsilvapt** [comment]
Added decision and notes here: https://github.com/surface-security/guidelines/blob/main/README.md#releases

Feel free to open any issue and/or PR to submit changes as you deem necessary.

**Comment by fopina** [comment]
LGTM 👍

**Comment by gsilvapt** [comment]
Have to redo all libs workflows though. Thanks!
